CREATE DATABASE IF NOT EXISTS enterprise CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS enterpriseRegister (
    id INT PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS employeeRegister (
    id INT PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    enterpriseName VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS notesRegister (
    id INT PRIMARY KEY AUTOINCREMENT NOT NULL,
    vendedor VARCHAR(100) NOT NULL,
    cliente VARCHAR(100) NOT NULL,
    produto VARCHAR(100) NOT NULL,
    price DECIMAL(6, 2) NOT NULL
);